const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'src/data/course.js');
let src = fs.readFileSync(file, 'utf8');

const map = [
  ["'Nhan dien dau hieu hinh anh va video'", "'Nhận diện dấu hiệu hình ảnh và video'"],
  ["'90-100 phut'", "'90-100 phút'"],
  ["'Intermediate'", "'Trung cấp'"],
  ["'Minh, 31 tuoi, lam truyen thong. Dong nghiep gui vao nhom chat mot video: lanh dao cap cao dang phat bieu dieu gi gay tranh cai. Moi nguoi dang phan ung. Minh nhin video — chat luong tot, khuon mat quen thuoc, am thanh ro. Nhung co gi do khong on. Lam the nao Minh biet phai nhin vao dau?'",
   "'Minh, 31 tuổi, làm truyền thông. Đồng nghiệp gửi vào nhóm chat một video: lãnh đạo cấp cao đang phát biểu điều gì gây tranh cãi. Mọi người đang phản ứng. Minh nhìn video — chất lượng tốt, khuôn mặt quen thuộc, âm thanh rõ. Nhưng có gì đó không ổn. Làm thế nào Minh biết phải nhìn vào đâu?'"],
  ["'Nhan dien it nhat 10 dau hieu nghi van cu the trong hinh anh va video.'",
   "'Nhận diện ít nhất 10 dấu hiệu nghi vấn cụ thể trong hình ảnh và video.'"],
  ["'Ap dung phuong phap SCAN de quan sat co he thong tu khuon mat den boi canh.'",
   "'Áp dụng phương pháp SCAN để quan sát có hệ thống từ khuôn mặt đến bối cảnh.'"],
  ["'Hieu gioi han cua quan sat bang mat thuong va khi nao can cong cu ho tro.'",
   "'Hiểu giới hạn của quan sát bằng mắt thường và khi nào cần công cụ hỗ trợ.'"],
  ["'4.1 Khuon mat — vung trong tam cua deepfake'", "'4.1 Khuôn mặt — vùng trọng tâm của deepfake'"],
  ["'4.2 Mat, mieng va bieu cam'", "'4.2 Mắt, miệng và biểu cảm'"],
  ["'4.3 Chuyen dong, artifact va thoi gian'", "'4.3 Chuyển động, artifact và thời gian'"],
  ["'4.4 Anh sang, nen va boi canh'", "'4.4 Ánh sáng, nền và bối cảnh'"],
  ["'4.5 Quy trinh SCAN va gioi han quan sat'", "'4.5 Quy trình SCAN và giới hạn quan sát'"],
  ["'Tai sao deepfake tap trung vao khuon mat'", "'Tại sao deepfake tập trung vào khuôn mặt'"],
  ["'Vien mat, toc va ranh gioi da'", "'Viền mặt, tóc và ranh giới da'"],
  ["'Ket cau da: lo chan long, nep nhan, chi tiet nho'", "'Kết cấu da: lỗ chân lông, nếp nhăn, chi tiết nhỏ'"],
  ["'Mau sac da va anh sang khong nhat quan'", "'Màu sắc da và ánh sáng không nhất quán'"],
  ["'Chuyen dong mat va chop mat bat thuong'", "'Chuyển động mắt và chớp mắt bất thường'"],
  ["'Dong bo moi — am thanh (lip sync)'", "'Đồng bộ môi — âm thanh (lip sync)'"],
  ["'Bieu cam cam xuc: tu nhien hay may moc?'", "'Biểu cảm cảm xúc: tự nhiên hay máy móc?'"],
  ["'Chuyen dong dau, co va co the'", "'Chuyển động đầu, cổ và cơ thể'"],
  ["'Artifact, nhoe va meo o vung bien'", "'Artifact, nhòe và méo ở vùng biên'"],
  ["'Su nhat quan theo thoi gian trong video'", "'Sự nhất quán theo thời gian trong video'"],
  ["'Anh sang va bong toi mau thuan'", "'Ánh sáng và bóng tối mâu thuẫn'"],
  ["'Nen bi meo, bien dang hoac lap'", "'Nền bị méo, biến dạng hoặc lặp'"],
  ["'Chi tiet phu: tai, co, vai va phu kien'", "'Chi tiết phụ: tai, cổ, vai và phụ kiện'"],
  ["'Phuong phap SCAN: 4 buoc quan sat co he thong'", "'Phương pháp SCAN: 4 bước quan sát có hệ thống'"],
  ["'Checklist nhanh khi gap noi dung nghi van'", "'Checklist nhanh khi gặp nội dung nghi vấn'"],
  ["'Gioi han cua mat thuong va khi nao dung cong cu'", "'Giới hạn của mắt thường và khi nào dùng công cụ'"],
  ["'Deepfake tap trung vao vung oval khuon mat — vien va toc thuong kem chinh xac hon.'",
   "'Deepfake tập trung vào vùng oval khuôn mặt — viền và tóc thường kém chính xác hơn.'"],
  ["'Da deepfake thuong qua min: thieu lo chan long, nep nhan va chi tiet nho tu nhien.'",
   "'Da deepfake thường quá mịn: thiếu lỗ chân lông, nếp nhăn và chi tiết nhỏ tự nhiên.'"],
  ["'Anh sang va mau sac da khong nhat quan giua khuon mat va co/vai la dau hieu dang chu y.'",
   "'Ánh sáng và màu sắc da không nhất quán giữa khuôn mặt và cổ/vai là dấu hiệu đáng chú ý.'"],
  ["'Mat: chu y chop mat bat thuong va anh phan chieu khong khop voi nguon sang.'",
   "'Mắt: chú ý chớp mắt bất thường và ánh phản chiếu không khớp với nguồn sáng.'"],
  ["'Lip sync: xem khong tieng truoc, sau do xem lai co tieng de phat hien do tre.'",
   "'Lip sync: xem không tiếng trước, sau đó xem lại có tiếng để phát hiện độ trễ.'"],
  ["'Bieu cam deepfake thuong qua doi xung va thieu vi chuyen dong co mat nho.'",
   "'Biểu cảm deepfake thường quá đối xứng và thiếu vi chuyển động cơ mặt nhỏ.'"],
  ["'Chuyen dong dau va co khong nhat quan, dac biet khi tay cham vao mat, la dau hieu manh.'",
   "'Chuyển động đầu và cổ không nhất quán, đặc biệt khi tay chạm vào mặt, là dấu hiệu mạnh.'"],
  ["'Artifact thuong xuat hien o vung bien khuon mat va tai — ro nhat khi tua cham video.'",
   "'Artifact thường xuất hiện ở vùng biên khuôn mặt và tai — rõ nhất khi tua chậm video.'"],
  ["'Su thieu nhat quan theo thoi gian (chi tiet bien mat/xuat hien) la loi dac trung cua deepfake.'",
   "'Sự thiếu nhất quán theo thời gian (chi tiết biến mất/xuất hiện) là lỗi đặc trưng của deepfake.'"],
  ["'Anh sang la bang chung vat ly: bong mui, bong nen va catchlight trong mat phai nhat quan.'",
   "'Ánh sáng là bằng chứng vật lý: bóng mũi, bóng nền và catchlight trong mắt phải nhất quán.'"],
  ["'Nen bi meo xung quanh vien dau la dau hieu cua deepfake xu ly kem.'",
   "'Nền bị méo xung quanh viền đầu là dấu hiệu của deepfake xử lý kém.'"],
  ["'Kinh mat, bong tai va do trang suc la diem kiem tra nhanh — deepfake thuong xu ly nhung thu nay kem nhat.'",
   "'Kính mắt, bông tai và đồ trang sức là điểm kiểm tra nhanh — deepfake thường xử lý những thứ này kém nhất.'"],
  ["'SCAN — Surface, Close-up, Action, Narrative — la 4 buoc quan sat co he thong.'",
   "'SCAN — Surface, Close-up, Action, Narrative — là 4 bước quan sát có hệ thống.'"],
  ["'Checklist 10 diem: 3-4 dau hieu duong tinh tro len la muc nghi van can kiem chung them.'",
   "'Checklist 10 điểm: 3-4 dấu hiệu dương tính trở lên là mức nghi vấn cần kiểm chứng thêm.'"],
  ["'Mat thuong co gioi han — dung cong cu khi noi dung co tac dong lon hoac nghi van cao.'",
   "'Mắt thường có giới hạn — dùng công cụ khi nội dung có tác động lớn hoặc nghi vấn cao.'"],
  // quiz answer options
  ["'Vien mat, toc va vung ngoai oval khuon mat'", "'Viền mặt, tóc và vùng ngoài oval khuôn mặt'"],
  ["'Trung tam khuon mat (mui)'", "'Trung tâm khuôn mặt (mũi)'"],
  ["'Mau sac nen'", "'Màu sắc nền'"],
  ["'Phu de video'", "'Phụ đề video'"],
  ["'Qua min, thieu lo chan long va chi tiet tu nhien'", "'Quá mịn, thiếu lỗ chân lông và chi tiết tự nhiên'"],
  ["'Qua tho va nhieu dom'", "'Quá thô và nhiều đốm'"],
  ["'Co mau xanh la'", "'Có màu xanh lá'"],
  ["'Luon trong rat that'", "'Luôn trông rất thật'"],
  ["'Huong bong tren khuon mat voi bong tren vat the xung quanh'", "'Hướng bóng trên khuôn mặt với bóng trên vật thể xung quanh'"],
  ["'Am luong am thanh voi do sang man hinh'", "'Âm lượng âm thanh với độ sáng màn hình'"],
  ["'Toc do chuyen dong voi toc do audio'", "'Tốc độ chuyển động với tốc độ audio'"],
  ["'Mau toc voi mau nen'", "'Màu tóc với màu nền'"],
  ["'Thieu chi tiet soi toc rieng le, trong nhu mot khoi dong nhat'", "'Thiếu chi tiết sợi tóc riêng lẻ, trông như một khối đồng nhất'"],
  ["'Mau qua toi'", "'Màu quá tối'"],
  ["'Di chuyen qua nhanh'", "'Di chuyển quá nhanh'"],
  ["'Luon bi che khuat'", "'Luôn bị che khuất'"],
  ["'15-20 lan moi phut, khong deu dan'", "'15-20 lần mỗi phút, không đều đặn'"],
  ["'1-2 lan moi phut, deu dan'", "'1-2 lần mỗi phút, đều đặn'"],
  ["'50 lan moi phut'", "'50 lần mỗi phút'"],
  ["'Moi 5 giay chinh xac'", "'Mỗi 5 giây chính xác'"],
  ["'Xem khong tieng truoc, sau do xem lai co tieng'", "'Xem không tiếng trước, sau đó xem lại có tiếng'"],
  ["'Tat man hinh va chi nghe'", "'Tắt màn hình và chỉ nghe'"],
  ["'Tang toc video len 2x'", "'Tăng tốc video lên 2x'"],
  ["'Xem tren dien thoai thay vi may tinh'", "'Xem trên điện thoại thay vì máy tính'"],
  ["'Bat doi xung nho va co vi chuyen dong co mat'", "'Bất đối xứng nhỏ và có vi chuyển động cơ mặt'"],
  ["'Hoan toan doi xung va tron tru'", "'Hoàn toàn đối xứng và trơn tru'"],
  ["'Khong bao gio thay doi nhanh'", "'Không bao giờ thay đổi nhanh'"],
  ["'Luon can doi hai ben'", "'Luôn cân đối hai bên'"],
  ["'Khong khop voi nguon sang thuc trong canh quay'", "'Không khớp với nguồn sáng thực trong cảnh quay'"],
  ["'Qua sang'", "'Quá sáng'"],
  ["'Qua toi'", "'Quá tối'"],
  ["'Khong ton tai anh phan chieu'", "'Không tồn tại ánh phản chiếu'"],
  ["'Khi tay nhan vat cham vao khuon mat'", "'Khi tay nhân vật chạm vào khuôn mặt'"],
  ["'Khi nhan vat dung yen'", "'Khi nhân vật đứng yên'"],
  ["'Khi video co am nhac nen'", "'Khi video có âm nhạc nền'"],
  ["'Khi video co phu de'", "'Khi video có phụ đề'"],
  ["'Chung xuat hien khong lien tuc va chi ro khi tua cham'", "'Chúng xuất hiện không liên tục và chỉ rõ khi tua chậm'"],
  ["'Chung bi an boi am thanh'", "'Chúng bị ẩn bởi âm thanh'"],
  ["'Man hinh do phan giai thap che di'", "'Màn hình độ phân giải thấp che đi'"],
  ["'Chung chi xuat hien o dinh dang .mp4'", "'Chúng chỉ xuất hiện ở định dạng .mp4'"],
  ["'Tai — do cau truc 3D phuc tap'", "'Tai — do cấu trúc 3D phức tạp'"],
  ["'Mui — do mau sac'", "'Mũi — do màu sắc'"],
  ["'Tran — do thieu du lieu huan luyen'", "'Trán — do thiếu dữ liệu huấn luyện'"],
  ["'Moi — do chuyen dong'", "'Môi — do chuyển động'"],
  ["'Bong do duoi mui, bong vat the xung quanh va catchlight trong mat'", "'Bóng đổ dưới mũi, bóng vật thể xung quanh và catchlight trong mắt'"],
  ["'Am luong va do sang man hinh'", "'Âm lượng và độ sáng màn hình'"],
  ["'Mau toc va mau nen'", "'Màu tóc và màu nền'"],
  ["'Toc do chuyen dong va toc do noi'", "'Tốc độ chuyển động và tốc độ nói'"],
  ["'Phan chieu trong kinh phai khop voi moi truong thuc — deepfake thuong xu ly sai dieu nay'",
   "'Phản chiếu trong kính phải khớp với môi trường thực — deepfake thường xử lý sai điều này'"],
  ["'Kinh luon bi deepfake bo qua hoan toan'", "'Kính luôn bị deepfake bỏ qua hoàn toàn'"],
  ["'Kinh lam lo mau mat that'", "'Kính làm lộ màu mắt thật'"],
  ["'Deepfake khong the tai tao gong kinh'", "'Deepfake không thể tái tạo gọng kính'"],
  ["'Thuat toan deepfake dang xu ly vung do khong hoan hao'", "'Thuật toán deepfake đang xử lý vùng đó không hoàn hảo'"],
  ["'Camera co van de'", "'Camera có vấn đề'"],
  ["'Video duoc quay o do phan giai thap'", "'Video được quay ở độ phân giải thấp'"],
  ["'Anh sang qua manh'", "'Ánh sáng quá mạnh'"],
  ["'3-4 diem tro len'", "'3-4 điểm trở lên'"],
  ["'10/10 diem'", "'10/10 điểm'"],
  ["'Chi can 1 diem'", "'Chỉ cần 1 điểm'"],
  ["'It nhat 8 diem'", "'Ít nhất 8 điểm'"],
  ["'Deepfake chat luong cao ngay cang kho phat hien va dieu kien xem anh huong lon'",
   "'Deepfake chất lượng cao ngày càng khó phát hiện và điều kiện xem ảnh hưởng lớn'"],
  ["'Mat nguoi khong the nhin mau sac chinh xac'", "'Mắt người không thể nhìn màu sắc chính xác'"],
  ["'Mat nguoi chi phat hien duoc chuyen dong'", "'Mắt người chỉ phát hiện được chuyển động'"],
  ["'Mat nguoi khong the so sanh hai video cung luc'", "'Mắt người không thể so sánh hai video cùng lúc'"],
  ["'Khi noi dung co tac dong lon hoac nhieu diem checklist cho ket qua nghi van'",
   "'Khi nội dung có tác động lớn hoặc nhiều điểm checklist cho kết quả nghi vấn'"],
  ["'Luon luon dung cong cu, khong can quan sat bang mat'", "'Luôn luôn dùng công cụ, không cần quan sát bằng mắt'"],
  ["'Chi khi noi dung lien quan den chinh tri'", "'Chỉ khi nội dung liên quan đến chính trị'"],
  ["'Chi khi ban la chuyen gia bao mat'", "'Chỉ khi bạn là chuyên gia bảo mật'"],
  // quiz questions
  ["q('Vung nao cua deepfake thuong kem chinh xac nhat?'", "q('Vùng nào của deepfake thường kém chính xác nhất?'"],
  ["q('Da trong deepfake thuong co dac diem gi?'", "q('Da trong deepfake thường có đặc điểm gì?'"],
  ["q('Khi kiem tra anh sang trong video, nen so sanh dieu gi?'", "q('Khi kiểm tra ánh sáng trong video, nên so sánh điều gì?'"],
  ["q('Toc trong deepfake thuong co van de gi?'", "q('Tóc trong deepfake thường có vấn đề gì?'"],
  ["q('Tan suat chop mat binh thuong cua nguoi la bao nhieu?'", "q('Tần suất chớp mắt bình thường của người là bao nhiêu?'"],
  ["q('Cach nao giup phat hien lip sync bat thuong hieu qua?'", "q('Cách nào giúp phát hiện lip sync bất thường hiệu quả?'"],
  ["q('Bieu cam khuon mat that thuong co dac diem gi?'", "q('Biểu cảm khuôn mặt thật thường có đặc điểm gì?'"],
  ["q('Anh phan chieu trong mat cua deepfake thuong co van de gi?'", "q('Ánh phản chiếu trong mắt của deepfake thường có vấn đề gì?'"],
  ["q('Khi nao deepfake video thuong bi lo ro nhat?'", "q('Khi nào deepfake video thường bị lộ rõ nhất?'"],
  ["q('Vi sao artifact thuong khong thay o toc do binh thuong?'", "q('Vì sao artifact thường không thấy ở tốc độ bình thường?'"],
  ["q('Vung nao cua khuon mat thuong bi deepfake xu ly kem nhat?'", "q('Vùng nào của khuôn mặt thường bị deepfake xử lý kém nhất?'"],
  ["q('Khi kiem tra anh sang, can so sanh dong thoi nhung gi?'", "q('Khi kiểm tra ánh sáng, cần so sánh đồng thời những gì?'"],
  ["q('Tai sao kinh mat la diem kiem tra huu ich?'", "q('Tại sao kính mắt là điểm kiểm tra hữu ích?'"],
  ["q('Nen bi meo xung quanh dau nhan vat thuong goi y dieu gi?'", "q('Nền bị méo xung quanh đầu nhân vật thường gợi ý điều gì?'"],
  ["q('SCAN la viet tat cua gi?'", "q('SCAN là viết tắt của gì?'"],
  ["q('Bao nhieu diem duong tinh trong checklist 10 diem la muc nghi van cao?'", "q('Bao nhiêu điểm dương tính trong checklist 10 điểm là mức nghi vấn cao?'"],
  ["q('Gioi han quan trong nhat cua quan sat mat thuong la gi?'", "q('Giới hạn quan trọng nhất của quan sát mắt thường là gì?'"],
  ["q('Nen dung cong cu phan tich khi nao?'", "q('Nên dùng công cụ phân tích khi nào?'"],
  ["q('Vung nao cua deepfake video thuong kem chinh xac nhat?'", "q('Vùng nào của deepfake video thường kém chính xác nhất?'"],
  ["q('Da trong deepfake thuong co dac diem gi noi bat?'", "q('Da trong deepfake thường có đặc điểm gì nổi bật?'"],
  ["q('Cach nao giup phat hien lip sync bat thuong hieu qua nhat?'", "q('Cách nào giúp phát hiện lip sync bất thường hiệu quả nhất?'"],
  ["q('SCAN trong quy trinh quan sat la viet tat cua gi?'", "q('SCAN trong quy trình quan sát là viết tắt của gì?'"],
  ["q('Tai sao tai la vung huu ich de kiem tra deepfake?'", "q('Tại sao tai là vùng hữu ích để kiểm tra deepfake?'"],
  ["q('Khi nao artifact trong deepfake thuong ro nhat?'", "q('Khi nào artifact trong deepfake thường rõ nhất?'"],
  ["q('Checklist 10 diem duoc dung de lam gi?'", "q('Checklist 10 điểm được dùng để làm gì?'"],
  ["q('Khi nao nen dung cong cu phan tich deepfake thay vi chi dung mat thuong?'", "q('Khi nào nên dùng công cụ phân tích deepfake thay vì chỉ dùng mắt thường?'"],
  // more quiz options
  ["'Vien mat, toc va cac chi tiet ngoai oval khuon mat'", "'Viền mặt, tóc và các chi tiết ngoài oval khuôn mặt'"],
  ["'Trung tam khuon mat'", "'Trung tâm khuôn mặt'"],
  ["'Mau sac tong the video'", "'Màu sắc tổng thể video'"],
  ["'Chat luong am thanh'", "'Chất lượng âm thanh'"],
  ["'Co nhieu dom va vet ban'", "'Có nhiều đốm và vết bẩn'"],
  ["'Mau xanh la dac trung'", "'Màu xanh lá đặc trưng'"],
  ["'Luon trong rat that va khong the phan biet'", "'Luôn trông rất thật và không thể phân biệt'"],
  ["'Xem video khong tieng truoc de quen voi chuyen dong moi, sau do xem lai co tieng'",
   "'Xem video không tiếng trước để quen với chuyển động môi, sau đó xem lại có tiếng'"],
  ["'Tat man hinh va chi nghe am thanh'", "'Tắt màn hình và chỉ nghe âm thanh'"],
  ["'Tang toc do phat len 3x'", "'Tăng tốc độ phát lên 3x'"],
  ["'So sanh voi video khac cua cung nguoi'", "'So sánh với video khác của cùng người'"],
  ["'Cau truc 3D phuc tap khien deepfake thuong xu ly tai kem'", "'Cấu trúc 3D phức tạp khiến deepfake thường xử lý tai kém'"],
  ["'Tai khong bao gio xuat hien trong deepfake'", "'Tai không bao giờ xuất hiện trong deepfake'"],
  ["'Tai co mau sac dac biet de phat hien'", "'Tai có màu sắc đặc biệt dễ phát hiện'"],
  ["'Deepfake luon xoa tai khoi video'", "'Deepfake luôn xóa tai khỏi video'"],
  ["'Khi tua cham video (0.25x hoac 0.5x)'", "'Khi tua chậm video (0.25x hoặc 0.5x)'"],
  ["'Khi xem o toc do binh thuong'", "'Khi xem ở tốc độ bình thường'"],
  ["'Khi tang am luong'", "'Khi tăng âm lượng'"],
  ["'Khi doi sang man hinh lon hon'", "'Khi đổi sang màn hình lớn hơn'"],
  ["'Danh gia nhanh muc do nghi van va quyet dinh co can kiem chung them khong'",
   "'Đánh giá nhanh mức độ nghi vấn và quyết định có cần kiểm chứng thêm không'"],
  ["'Ket luan chac chan video la deepfake'", "'Kết luận chắc chắn video là deepfake'"],
  ["'Thay the hoan toan cong cu phan tich'", "'Thay thế hoàn toàn công cụ phân tích'"],
  ["'Bao cao video len co quan chuc nang'", "'Báo cáo video lên cơ quan chức năng'"],
  ["'Khi noi dung co tac dong lon va nhieu diem nghi van trong checklist'",
   "'Khi nội dung có tác động lớn và nhiều điểm nghi vấn trong checklist'"],
  ["'Chi khi la chuyen gia bao mat'", "'Chỉ khi là chuyên gia bảo mật'"],
  ["'Luon luon, mat thuong khong co gia tri'", "'Luôn luôn, mắt thường không có giá trị'"],
  ["'Chi khi video dai hon 10 phut'", "'Chỉ khi video dài hơn 10 phút'"],
];

let count = 0;
for (const [from, to] of map) {
  if (from === to) continue;
  if (src.includes(from)) {
    src = src.split(from).join(to);
    count++;
  } else {
    // try to find it with unicode escapes resolved
  }
}

fs.writeFileSync(file, src, 'utf8');
console.log('Done. Applied ' + count + ' replacements.');
